App_Login/urls.py
from django.urls import path
from App_Login import views
from .views import sign_up, DcmAdminSignUpview, DoctorSignUpview, TechnicianSignUpview, CreatePatient

app_name = 'App_Login'

urlpatterns = [
    path('signup/', sign_up,  name='signup'),
    path('dcmadminsignup/', DcmAdminSignUpview.as_view(),  name='dcmadminsignup'),
    path('view_dcmadmin/', views.View_DcmAdmin, name='view_dcmadmin'),
    path('delete_dcmadmin(<int:pid>)', views.Delete_DcmAdmin, name='delete_dcmadmin'),
    path('doctorsignup/', DoctorSignUpview.as_view(),  name='doctorsignup'),
    path('view_doctor/', views.View_Doctor, name='view_doctor'),
    path('delete_doctor/<int:pid>/', views.delete_doctor, name='delete_doctor'),
    path('techniciansignup/', TechnicianSignUpview.as_view(),  name='techniciansignup'),
    path('view_technician/', views.View_Technician, name='view_technician'),
    path('delete_technician/<int:pid>/', views.Delete_Technician, name='delete_technician'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('doctor_profile/', views.doctor_profile, name='doctor_profile'),
    path('doctor_profile_2/<int:pid>/', views.doctor_profile_2, name='doctor_profile_2'),
    path('technician_profile/', views.technician_profile, name='technician_profile'),
    path('dcmadmin_profile/', views.dcmadmin_profile, name='dcmadmin_profile'),
    path('patient_profile(<int:pid>)', views.patient_profile, name='patient_profile'),
    path('change-profile/', views.user_change, name='user_change'),
    path('change-dcmadmin-profile/', views.dcmadmin_change, name='dcmadmin_change'),
    path('change-doctor-profile/', views.doctor_change, name='doctor_change'),
    path('change-technician-profile/', views.technician_change, name='technician_change'),
    path('password/', views.pass_change, name='pass_change'),
    path('add-picture/', views.add_pro_pic, name='add_pro_pic'),
    path('add-doctor-picture/', views.add_doctor_pro_pic, name='add_doctor_pro_pic'),
    path('add-patient-pic/', views.add_patient_pic, name='add_patient_pic'),
    path('change-picture/', views.change_pro_pic, name='change_pro_pic'),
    path('change-doctor-picture/', views.change_doctor_pro_pic, name='change_doctor_pro_pic'),
    path('change-patient-pic(<int:pid>)', views.change_patient_pic, name='change_patient_pic'),
    path('view_patient/', views.View_Patient, name='view_patient'),
    path('add_patient/', views.CreatePatient, name='add_patient'),
    path('delete_patient(<int:pid>)', views.Delete_Patient, name='delete_patient'),
    path('edit_patient/<pk>/', views.UpdateDcmPatient.as_view(), name='edit_patient')
    
]

    

Core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Define your URL patterns here
]

Diagnostic_Center/urls.py
from django.contrib import admin
from django.urls import path
from Diagnostic_Center import views
from Diagnostic_Center.views import *

app_name = 'Diagnostic_Center'

urlpatterns = [
    path('', views.blog_list, name='blog_list'),
    path('view_prescription/', views.view_prescription, name='view_prescription'),
    path('view_test_report/', views.view_test_report, name='view_test_report'),
    path('view_package_test_report/', views.view_package_test_report, name='view_package_test_report'),
    path('view_appointment_doctor/', views.view_appointment_doctor, name='view_appointment_doctor'),
    path('view_appointment_test/', views.view_appointment_test, name='view_appointment_test'),
    path('view_appointment_package_test/', views.view_appointment_package_test, name='view_appointment_package_test'),
    path('create_appointment_package_test_2/<int:package_id>/', views.create_appointment_package_test_2, name='create_appointment_package_test_2'),
    path('create_appointment_doctor/', views.create_appointment_doctor, name='create_appointment_doctor'),
    path('create_appointment_doctor_2/<int:doctor_id>/', views.create_appointment_doctor_2, name='create_appointment_doctor_2'),
    path('create_appointment_test/', views.create_appointment_test, name='create_appointment_test'),
    path('create_test_report(<int:aid>)', views.create_test_report, name='create_test_report'),
    path(' create_package_test_report(<int:aid>)', views.create_package_test_report, name='create_package_test_report'),
    path('create_appointment_test_2/<int:test_id>/', views.create_appointment_test_2, name='create_appointment_test_2'),
    path('create_appointment_package_test/', views.create_appointment_package_test, name='create_appointment_package_test'),
    path('create_prescription(<int:aid>)', views.create_prescription, name='create_prescription'),
    path('delete_appointment_doctor(<int:pid>)', views.delete_appointment_doctor, name='delete_appointment_doctor'),
    path('update_doctor_appointment/<pk>/', views.UpdateDoctorAppointment.as_view(), name='update_doctor_appointment'),
    path('update_test_appointment/<pk>/', views.UpdateTestAppointment.as_view(), name='update_test_appointment'),
    path('update_package_test_appointment/<pk>/', views.UpdatePackageTestAppointment.as_view(), name='update_package_test_appointment'),
    path('delete_appointment_test(<int:pid>)', views.delete_appointment_test, name='delete_appointment_test'),
    path('delete_appointment_package_test(<int:pid>)', views.delete_appointment_package_test, name='delete_appointment_package_test'),
    path('delete_prescription(<int:pid>)', views.delete_prescription, name='delete_prescription'),
    path('update_prescription/<pk>/', views.UpdatePrescription.as_view(), name='edit_prescription'),
    path('update_prescription(<int:pid>)', views.update_prescription, name='edit_prescription_2'),
    path('prescription_detail(<int:pid>)', views.prescription_detail, name='prescription_detail'),
    path('doctor_appointment_details(<int:aid>)', views.doctor_appointment_details, name='doctor_appointment_details'),
    path('view_test/', views.view_test, name='view_test'),
    path('create_test/', views.create_test, name='create_test'),
    path('delete_test(<int:pid>)', views.delete_test, name='delete_test'),
    path('delete_test_report(<int:pid>)', views.delete_test_report, name='delete_test_report'),
    path('delete_package_test_report(<int:pid>)', views.delete_package_test_report, name='delete_package_test_report'),
    path('update_test/<pk>/', views.UpdateTest.as_view(), name='update_test'),
    path('update_test_report/<pk>/', views.UpdateTestReport.as_view(), name='update_test_report'),
    path('update_package_test_report/<pk>/', views.UpdatePackageTestReport.as_view(), name='update_package_test_report'),
    path('view_package/', views.view_package, name='view_package'),
    path('create_package/', views.create_package, name='create_package'),
    path('package_detail(<int:pid>)', views.package_detail, name='package_detail'),
    path('package_update/<pk>/', views.UpdatePackage.as_view(), name='package_update'),
    path('delete_package(<int:pid>)', views.delete_package, name='delete_package'),
    path('view_medicine/', views.view_medicine, name='view_medicine'),
    path('create_medicine/', views.create_medicine, name='create_medicine'),
    path('update_medicine/<pk>/', views.UpdateMedicine.as_view(), name='update_medicine'),
    path('delete_medicine(<int:pid>)', views.delete_medicine, name='delete_medicine'),
    
]

Diagnostic_Center_Management03/urls.py
from django.contrib import admin
from django.urls import path, include 
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('diagnostic_center/', include('Diagnostic_Center.urls')),
    path('core/', include('Core.urls')),
    path('', views.Index, name='index'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Login/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from Core.models import Department

# Create your models here.

class User(AbstractUser):
    is_dcmadmin = models.BooleanField(default=False)
    is_doctor = models.BooleanField(default=False)
    is_technician = models.BooleanField(default=False)
    is_attendent = models.BooleanField(default=False)
    profile_pic = models.ImageField(upload_to='profile_pics', null=True, blank=True)
    
class DcmAdmin(models.Model):
    user = models.OneToOneField(User, related_name='admin_profile', on_delete=models.CASCADE, primary_key=True)
    dcmadmin_full_name = models.CharField(max_length=60, null=True, blank=True)
    dcmadmin_phone = models.IntegerField(blank=True, null=True)
    dcmadmin_department =models.CharField(max_length=60, null=True, blank=True)



    def __str__(self):
    	return self.user.username
 
class Attendent(models.Model):
    user = models.OneToOneField(User, related_name='attendent_profile', on_delete=models.CASCADE, primary_key=True)


    def __str__(self):
    	return self.user.username
 
class DcmPatient(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='dcmpatient_profile')
    patient_image = models.ImageField(upload_to='profile_pics', null=True, blank=True)
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=264, unique=True, null=True, blank=True)
    gender = models.CharField(max_length=50, null=True, blank=True)
    blood_group = (
        ("A+", "A+"),
        ("A-", "A-"),
        ("B+", "B+"),
        ("B-", "B-"),
        ("O+", "O+"),
        ("O-", "O-"),
        ("AB+", "AB+"),
        ("AB-", "AB-"),
    
    )
    patient_blood_group = models.CharField(max_length=20,choices= blood_group, null=True, blank=True)
    mobile = models.IntegerField(null=True, blank=True)
    age = models.IntegerField(null=True, blank=True)
    address = models.CharField(max_length=150, null=True, blank=True)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('first_app:patient_details', kwargs={'pk':self.pk})
 
 
class Doctor(models.Model):
    user = models.OneToOneField(User, related_name='doctor_profile', on_delete=models.CASCADE, primary_key=True)
    doctor_full_name = models.CharField(max_length=200, null=True, blank=True)
    phone = models.IntegerField(blank=True, null=True)
    spe = models.CharField(max_length=200, null=True, blank=True)
    designation =models.CharField(max_length=200, null=True, blank=True)
    degree = models.CharField(max_length=200, null=True, blank=True)
    current_working_place=models.CharField(max_length=200, null=True, blank=True)
    mbbs_institution = models.CharField(max_length=200, null=True, blank=True)
    post_graduation_institution = models.CharField(max_length=200, null=True, blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', null=True, blank=True)
    


    def __str__(self):
    	return self.doctor_full_name
 

class Technician(models.Model):
    user = models.OneToOneField(User, related_name='technician_profile', on_delete=models.CASCADE, primary_key=True)
    technician_full_name = models.CharField(max_length=100, null=True, blank=True)
    phone = models.IntegerField(blank=True, null=True)
    designation = models.CharField(max_length=30, blank=True, null=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, null = True, blank = True)


    def __str__(self):
    	return self.technician_full_name
 
class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name = 'user_profile', on_delete=models.CASCADE, null=True, blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True, null=True)


class DoctorProfile(models.Model):
    doctor = models.OneToOneField(Doctor, related_name = 'doctor_profile', on_delete=models.CASCADE, null=True, blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', null=True, blank=True)

class TechnicianProfile(models.Model):
    technician = models.OneToOneField(Technician, related_name = 'technician_profile', on_delete=models.CASCADE, null=True, blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', null=True, blank=True)
    
class DcmAdminProfile(models.Model):
    dcmadmin = models.OneToOneField(DcmAdmin, related_name = 'dcmadmin_profile', on_delete=models.CASCADE, null=True, blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', null=True, blank=True)

templates/App_Login/add_patient_pic.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 
{% block title_block %} Patient Profile {% endblock %} 
{% block body_block %}
<br>
<br>
<h2>Add Your Patient Profile Picture: </h2>
<form method="post" enctype="multipart/form-data">
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-sm">Add</button>
</form>

{% endblock %}

templates/App_Login/add_pro_pic.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 
{% block title_block %} Profile {% endblock %} 
{% block body_block %}
<h2>Add Your Profile Picture: </h2>
<form method="post" enctype="multipart/form-data">
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-sm">Add</button>
</form>
{% endblock %}

templates/App_Login/change_dcmadmin_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Change Profile {% endblock %} 
{% block body_block %}

<div class="container mt-5">
  <div class="card shadow">
    <h2 class="card-header text-center">Update Admin Profile</h2>
    <div class="card-body">
      <form method="POST" class="offset-sm-3 col-sm-6"> <!-- Center the form horizontally -->
        {% csrf_token %}
        
        <div class="form-group row">
          <label for="id_doctor_full_name" class="col-sm-3 col-form-label">Admin Full Name:</label>
          <div class="col-sm-9">
            {{ form.dcmadmin_full_name }}
          </div>
        </div>

        <div class="form-group row">
          <label for="id_phone" class="col-sm-3 col-form-label">Phone:</label>
          <div class="col-sm-9">
            {{ form.dcmadmin_phone }}
          </div>
        </div>

        <div class="form-group row">
          <label for="id_spe" class="col-sm-3 col-form-label">Department:</label>
          <div class="col-sm-9">
            {{ form.dcmadmin_department }}
          </div>
        </div>

        <div class="form-group row">
          <div class="col-sm-12 text-center"> <!-- Center the update button -->
            <button type="submit" class="btn btn-warning">Update</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}








templates/App_Login/change_pro_pic.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 
{% block title_block %} Profile {% endblock %} 
{% block body_block %}
<br>
<br>
<h2>Change Your Profile Picture: </h2>
<form method="post" enctype="multipart/form-data">
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-sm">Save</button>
</form>
{% endblock %}

templates/App_Login/change_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Change Profile {% endblock %} 
{% block body_block %}

<div class="container">
    <br>
    <br>
    <h2 class="text-center">Update Profile</h2>
    <form method="post">
      {% csrf_token %}
      <div class="row">
        <div class="col-md-6">
          <label>User Name</label>
          <input type="text" class="form-control" name="username" value="{{ user.username }}" required />
        </div>
        <div class="col-md-6">
          <label>Email</label>
          <input type="email" class="form-control" name="email" value="{{ user.email }}" required />
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <label>First Name</label>
          <input type="text" class="form-control" name="first_name" value="{{ user.first_name }}" required />
        </div>
        <div class="col-md-6">
          <label>Last Name</label>
          <input type="text" class="form-control" name="last_name" value="{{ user.last_name }}" required />
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <label>Password</label>
          <input type="password" class="form-control" name="password" required />
        </div>
        <div class="col-md-6">
          <label>Confirm Password</label>
          <input type="password" class="form-control" name="confirm_password" required />
        </div>
      </div>
      <br />
      <div class="row">
        <div class="col-md-6 offset-md-3">
          <input type="submit" value="Update Profile" class="btn btn-primary btn-block" />
        </div>
      </div>
    </form>
  </div>

{% endblock %}

templates/App_Login/doctor_profile.html
{% extends 'base.html' %} 
{% block title_block %}Doctor Profile{% endblock %} 
{% block body_block %}
<div class="container text-center">
  <h2>Your Profile</h2>
  {% if user.doctor_profile %}
  <img src='/media/{{ user.doctor_profile.profile_pic }}' class="rounded-circle" width="150px">
  <br><br>
  <a href="{% url 'App_Login:change_doctor_pro_pic' %}" class="btn btn-info btn-sm">Change Profile Picture</a>
  {% else %}
  <img src='/media/profile_pics/avatar-male.jpg' class="rounded-circle" width="150px"/>
  <br><br>
  <a href="{% url 'App_Login:add_doctor_pro_pic' %}" class="btn btn-info btn-sm">Add Profile Picture</a>
  {% endif %}
  <br><br>
  {% for doctor in doc %}
  <div class="card mx-auto" style="max-width: 500px;">
    <div class="card-body">
      <p class="card-text">Username: {{ user.username }}</p>
      <p class="card-text">Email: {{ user.email }}</p>
      <p class="card-text">Doctor Full Name: {{ doctor.doctor_full_name }}</p>
      <p class="card-text">Doctor Phone Number: {{ doctor.phone }}</p>
      <p class="card-text">Doctor Specialization: {{ doctor.spe }}</p>
      <p class="card-text">Doctor Designation: {{ doctor.designation }}</p>
      <p class="card-text">Doctor Degrees: {{ doctor.degree }}</p>
      <p class="card-text">Doctor Current Working Place: {{ doctor.current_working_place }}</p>
      <p class="card-text">Doctor Mbbs Institution: {{ doctor.mbbs_institution }}</p>
      <p class="card-text">Doctor Post Graduation Institution: {{ doctor.post_graduation_institution }}</p>
    </div>
  </div>
  {% endfor %}
  <br>
  <a href="{% url 'App_Login:doctor_change'  %}" class="btn btn-warning btn-sm">Change Profile Info</a>
</div>
{% endblock %}

templates/App_Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title_block %} Login {% endblock %}
{% block body_block %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h2 class="text-center">Login to Your Account</h2>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username">User Name </label>
                            <input type="text" class="form-control" name="username" id="username" required>
                        </div>
                        <div class="form-group">
                            <label for="password">Password</label>
                            <input type="password" class="form-control" name="password" id="password" required>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block">Log In</button>
                        </div>
                    </form>
                    {% comment %}
                    <div class="text-center">
                        <a href="#">Forgot Password?</a>
                    </div>
                    {% endcomment %} 
                    <p>Not Registered ! <a href="{% url 'App_Login:signup' %}">Signup Here</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/App_Login/signup.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %}
{% block title_block %} Create New Account {% endblock %} 
{% block body_block %} 

{% if registered %}
<div class="alert allert-success">
  Account Created Successfully! <a href="{% url 'App_Login:login' %}">Login Here</a>
</div>
{% else %}

<div class="container">
  <br>
  <br>
  <h2 class="text-center">Create An Account </h2>
  <form method="post" >
    {% csrf_token %}
    <div class="row">
      <div class="col-md-6">
        <label>User Name</label>
        <input type="text" class="form-control" name="username" required />
      </div>
      <div class="col-md-6">
        <label>Email</label>
        <input type="text" class="form-control" name="email" required />
      </div>
     
    </div>
    <div class="row">

      <div class="col-md-6">
        <label>User First Name</label>
        <input type="text" class="form-control" name="first_name" required />
      </div>
      <div class="col-md-6">
        <label>User Last Name</label>
        <input type="text" class="form-control" name="last_name" required />
      </div>
      
    </div>
    <div class="row">
      <div class="col-md-6">
        <label>Password</label>
        <input type="password" class="form-control" name="password1" required />
      </div>
      <div class="col-md-6">
        <label>Confirm Password</label>
        <input type="password" class="form-control" name="password2" required />
      </div>
    </div>
    <br />
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <input type="submit" value="Submit" class="form-control btn btn-primary" />
      </div>
    </div>
  </form>
</div>

<br />

<p>Already have an account ? <a href="{% url 'App_Login:login' %}">Login Here</a></p>

{% endif %} 
{% endblock %}

templates/App_Login/technician_profile.html
{% extends 'base.html' %} 
{% block title_block %}Technician Profile {% endblock %} 
{% block body_block %}
<style>
    .profile-container {
        text-align: center;
        margin-top: 50px;
    }
    .profile-info {
        background-color: #f9f9f9;
        border-radius: 10px;
        padding: 20px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        margin-bottom: 20px;
    }
    .profile-picture {
        border-radius: 50%;
    }
    .btn {
        margin-top: 10px;
    }
</style>

<div class="profile-container">
    <h2>Your Profile</h2>
    <div class="profile-info">
        {% if user.user_profile %}
            <img src='/media/{{user.user_profile.profile_pic}}' class="profile-picture" width="100px">
            <br>
            <br>
            <a href="{% url 'App_Login:change_pro_pic' %}" class="btn btn-info btn-sm">Change Profile Picture</a>
        {% else %}
            <img src='/media/profile_pics/avatar-male.jpg' class="profile-picture" width="100px"/>
            <br>
            <br>
            <a href="{% url 'App_Login:add_pro_pic' %}" class="btn btn-info btn-sm">Add Profile Picture</a>
        {% endif %}
    </div>
    {% for i in tec %}
        <div class="profile-info">
            <p>Username: {{ user.username }}</p>
            <p>Email: {{ user.email }}</p>
            <p>Technician Full Name: {{ i.technician_full_name }} </p>
            <p>Technician Phone Number: {{ i.phone }} </p>
            <p>Technician Designation : {{ i.designation }} </p>
            <p>Technician Department : {{ i.department }} </p>
        </div>
    {% endfor %}
    <a href="{% url 'App_Login:technician_change' %}" class="btn btn-warning btn-sm">Change Profile Info</a>
</div>
{% endblock %}

templates/App_Login/techniciansignup.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %}
{% block title_block %} Create Technician New Account {% endblock %} 
{% block body_block %} 
{% if registered %}
<div class="alert allert-success">
  Account Created Successfully! <a href="{% url 'App_Login:login' %}">Login Here</a>
</div>
{% else %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <h2 class="text-center mb-4">Create A Technician</h2>
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">User Name</label>
                    <input type="text" class="form-control" name="username" required>
                </div>
                <div class="form-group">
                    <label for="technician_full_name">Technician Full Name</label>
                    <input type="text" class="form-control" name="technician_full_name" required>
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" name="email" required>
                </div>
                <div class="form-group">
                    <label for="phone">Phone Number</label>
                    <input type="text" class="form-control" name="phone" required>
                </div>
                <div class="form-group">
                    <label for="designation">Designation</label>
                    <input type="text" class="form-control" name="designation" required>
                </div>
                <div class="form-group">
                    <label for="id_department">Department</label>
                    {{ form.department }}
                </div>
                <div class="form-group">
                    <label for="password1">Password</label>
                    <input type="password" class="form-control" name="password1" required>
                </div>
                <div class="form-group">
                    <label for="password2">Confirm Password</label>
                    <input type="password" class="form-control" name="password2" required>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">Submit</button>
                </div>
            </form>
            <p class="text-center">Already have an account? <a href="{% url 'App_Login:login' %}">Login Here</a></p>
        </div>
    </div>
</div>
{% endif %} 
{% endblock %}

templates/App_Login/view_doctor.html
{% extends 'base.html' %}
{% block title_block %} View Doctor {% endblock %} 
{% block body_block %}
<div class="container" style="margin-top:50px">
    <h2 class="text-center">Our Doctors</h2>
    {% if request.user.is_staff or user.is_dcmadmin %}
             <td><a href="{% url 'App_Login:doctorsignup' %}" class="btn btn-danger">Create Doctor</a></td>
    {% endif %}
    <br><br>
    <table class="table table-hover" id="example">
        <thead>
            <tr>
                <th>Doctor Full Name</th>
                <th>Specialization</th>
                {% comment %} <th>Designation</th>
                <th>Degrees</th> {% endcomment %}
                <th>Profile</th>
                
                {% if user.is_dcmadmin %}
                <th>Delete</th>
                {% elif  user.is_doctor   %}
                {% elif  user.is_technician  %}
                {% elif user.is_authenticated %}
                <th>Appointment</th>
                {% endif %}
                
            </tr>
        </thead>
        <tbody>
            {% for i in doc %} 
            <tr>
                <td>{{i.doctor_full_name}}</td>
                <td>{{i.spe}}</td>
                {% comment %} <td>{{i.designation}}</td>
                <td>{{i.degree}}</td> {% endcomment %}
                <td><a href="{% url 'App_Login:doctor_profile_2' i.user_id %}"  class="btn btn-danger">Profile</a></td>
                

                {% if user.is_dcmadmin %}
                <td><a href="{% url 'App_Login:delete_doctor' i.user_id %}" onClick="return confirm('Are you sure?')"  class="btn btn-danger">Delete</a></td>
                {% elif  user.is_doctor   %}
                {% elif  user.is_technician  %}
                {% elif user.is_authenticated %}
                <td><a href="{% url 'Diagnostic_Center:create_appointment_doctor_2' i.user_id %}" class="btn btn-danger">Create</a></td>
                {% comment %} <td><a href="{% url 'Diagnostic_Center:update_doctor_appointment' i.id  %}"  class="btn btn-danger">Update</a></td> {% endcomment %}
                {% endif %}
                
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>

{% endblock %}

templates/App_Login/view_technician.html
{% extends 'base.html' %}
{% block title_block %} VIEW TECHNICIAN {% endblock %} 
{% block body_block %}
<div class="container" style="margin-top:50px">
    <h2 class="text-center">View Technician</h2>
    {% if request.user.is_staff or user.is_dcmadmin %}
    <td><a href="{% url 'App_Login:techniciansignup' %}" class="btn btn-danger">Create Technician</a></td>
    {% endif %}
    <br><br>
    <table class="table table-hover" id="example">
        <thead>
            <tr>
                <th>Technician Full Name</th>
                <th>Phone Number</th>
                <th>Designation</th>
                <th>Departmentt</th>
                <th>Delete</th>
                
            </tr>
        </thead>
        <tbody>
            {% for i in tec %}
            <tr>
                <td>{{i.technician_full_name}}</td>
                <td>{{i.phone}}</td>
                <td>{{i.designation}}</td>
                <td>{{i.department}}</td>
                <td><a href="{% url 'App_Login:delete_technician' i.user_id %}" onClick="return confirm('Are you sure?')" class="btn btn-danger">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>

{% endblock %}