App_Login/urls.py
from django.urls import path
from App_Login import views
from .views import sign_up, DcmAdminSignUpview, DoctorSignUpview, TechnicianSignUpview, CreatePatient

app_name = 'App_Login'

urlpatterns = [
    path('signup/', sign_up,  name='signup'),
    path('dcmadminsignup/', DcmAdminSignUpview.as_view(),  name='dcmadminsignup'),
    path('view_dcmadmin/', views.View_DcmAdmin, name='view_dcmadmin'),
    path('delete_dcmadmin(<int:pid>)', views.Delete_DcmAdmin, name='delete_dcmadmin'),
    path('doctorsignup/', DoctorSignUpview.as_view(),  name='doctorsignup'),
    path('view_doctor/', views.View_Doctor, name='view_doctor'),
    path('delete_doctor/<int:pid>/', views.delete_doctor, name='delete_doctor'),
    path('techniciansignup/', TechnicianSignUpview.as_view(),  name='techniciansignup'),
    path('view_technician/', views.View_Technician, name='view_technician'),
    path('delete_technician/<int:pid>/', views.Delete_Technician, name='delete_technician'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('doctor_profile/', views.doctor_profile, name='doctor_profile'),
    path('doctor_profile_2/<int:pid>/', views.doctor_profile_2, name='doctor_profile_2'),
    path('technician_profile/', views.technician_profile, name='technician_profile'),
    path('dcmadmin_profile/', views.dcmadmin_profile, name='dcmadmin_profile'),
    path('patient_profile(<int:pid>)', views.patient_profile, name='patient_profile'),
    path('change-profile/', views.user_change, name='user_change'),
    path('change-dcmadmin-profile/', views.dcmadmin_change, name='dcmadmin_change'),
    path('change-doctor-profile/', views.doctor_change, name='doctor_change'),
    path('change-technician-profile/', views.technician_change, name='technician_change'),
    path('password/', views.pass_change, name='pass_change'),
    path('add-picture/', views.add_pro_pic, name='add_pro_pic'),
    path('add-doctor-picture/', views.add_doctor_pro_pic, name='add_doctor_pro_pic'),
    path('add-patient-pic/', views.add_patient_pic, name='add_patient_pic'),
    path('change-picture/', views.change_pro_pic, name='change_pro_pic'),
    path('change-doctor-picture/', views.change_doctor_pro_pic, name='change_doctor_pro_pic'),
    path('change-patient-pic(<int:pid>)', views.change_patient_pic, name='change_patient_pic'),
    path('view_patient/', views.View_Patient, name='view_patient'),
    path('add_patient/', views.CreatePatient, name='add_patient'),
    path('delete_patient(<int:pid>)', views.Delete_Patient, name='delete_patient'),
    path('edit_patient/<pk>/', views.UpdateDcmPatient.as_view(), name='edit_patient')
    
]

    

Core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Define your URL patterns here
]

Diagnostic_Center/urls.py
from django.contrib import admin
from django.urls import path
from Diagnostic_Center import views
from Diagnostic_Center.views import *

app_name = 'Diagnostic_Center'

urlpatterns = [
    path('', views.blog_list, name='blog_list'),
    path('view_prescription/', views.view_prescription, name='view_prescription'),
    path('view_test_report/', views.view_test_report, name='view_test_report'),
    path('view_package_test_report/', views.view_package_test_report, name='view_package_test_report'),
    path('view_appointment_doctor/', views.view_appointment_doctor, name='view_appointment_doctor'),
    path('view_appointment_test/', views.view_appointment_test, name='view_appointment_test'),
    path('view_appointment_package_test/', views.view_appointment_package_test, name='view_appointment_package_test'),
    path('create_appointment_package_test_2/<int:package_id>/', views.create_appointment_package_test_2, name='create_appointment_package_test_2'),
    path('create_appointment_doctor/', views.create_appointment_doctor, name='create_appointment_doctor'),
    path('create_appointment_doctor_2/<int:doctor_id>/', views.create_appointment_doctor_2, name='create_appointment_doctor_2'),
    path('create_appointment_test/', views.create_appointment_test, name='create_appointment_test'),
    path('create_test_report(<int:aid>)', views.create_test_report, name='create_test_report'),
    path(' create_package_test_report(<int:aid>)', views.create_package_test_report, name='create_package_test_report'),
    path('create_appointment_test_2/<int:test_id>/', views.create_appointment_test_2, name='create_appointment_test_2'),
    path('create_appointment_package_test/', views.create_appointment_package_test, name='create_appointment_package_test'),
    path('create_prescription(<int:aid>)', views.create_prescription, name='create_prescription'),
    path('delete_appointment_doctor(<int:pid>)', views.delete_appointment_doctor, name='delete_appointment_doctor'),
    path('update_doctor_appointment/<pk>/', views.UpdateDoctorAppointment.as_view(), name='update_doctor_appointment'),
    path('update_test_appointment/<pk>/', views.UpdateTestAppointment.as_view(), name='update_test_appointment'),
    path('update_package_test_appointment/<pk>/', views.UpdatePackageTestAppointment.as_view(), name='update_package_test_appointment'),
    path('delete_appointment_test(<int:pid>)', views.delete_appointment_test, name='delete_appointment_test'),
    path('delete_appointment_package_test(<int:pid>)', views.delete_appointment_package_test, name='delete_appointment_package_test'),
    path('delete_prescription(<int:pid>)', views.delete_prescription, name='delete_prescription'),
    path('update_prescription/<pk>/', views.UpdatePrescription.as_view(), name='edit_prescription'),
    path('update_prescription(<int:pid>)', views.update_prescription, name='edit_prescription_2'),
    path('prescription_detail(<int:pid>)', views.prescription_detail, name='prescription_detail'),
    path('doctor_appointment_details(<int:aid>)', views.doctor_appointment_details, name='doctor_appointment_details'),
    path('view_test/', views.view_test, name='view_test'),
    path('create_test/', views.create_test, name='create_test'),
    path('delete_test(<int:pid>)', views.delete_test, name='delete_test'),
    path('delete_test_report(<int:pid>)', views.delete_test_report, name='delete_test_report'),
    path('delete_package_test_report(<int:pid>)', views.delete_package_test_report, name='delete_package_test_report'),
    path('update_test/<pk>/', views.UpdateTest.as_view(), name='update_test'),
    path('update_test_report/<pk>/', views.UpdateTestReport.as_view(), name='update_test_report'),
    path('update_package_test_report/<pk>/', views.UpdatePackageTestReport.as_view(), name='update_package_test_report'),
    path('view_package/', views.view_package, name='view_package'),
    path('create_package/', views.create_package, name='create_package'),
    path('package_detail(<int:pid>)', views.package_detail, name='package_detail'),
    path('package_update/<pk>/', views.UpdatePackage.as_view(), name='package_update'),
    path('delete_package(<int:pid>)', views.delete_package, name='delete_package'),
    path('view_medicine/', views.view_medicine, name='view_medicine'),
    path('create_medicine/', views.create_medicine, name='create_medicine'),
    path('update_medicine/<pk>/', views.UpdateMedicine.as_view(), name='update_medicine'),
    path('delete_medicine(<int:pid>)', views.delete_medicine, name='delete_medicine'),
    
]

Diagnostic_Center_Management03/urls.py
from django.contrib import admin
from django.urls import path, include 
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('diagnostic_center/', include('Diagnostic_Center.urls')),
    path('core/', include('Core.urls')),
    path('', views.Index, name='index'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8" />
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"/>
        <!-- jQuery library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <!-- Popper JS -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <!-- Latest compiled JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

        <link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.4.2/css/buttons.dataTables.min.css">

<!-- Data Table CDN Start  -->
<script src="https://code.jquery.com/jquery-3.7.0.js"> </script>
<script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js" > </script>
<script src="https://cdn.datatables.net/buttons/2.4.2/js/dataTables.buttons.min.js" > </script>
<!-- Data Table CDN Start  -->
<script>
  $(document).ready(function() {
    $('#example').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            'copyHtml5',
            'excelHtml5',
            'csvHtml5',
            'pdfHtml5'
        ]
    } );
} );
</script>


    <title>{% block title_block %} Diagnostic Center Management {% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
    
      <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'index' %}">Home</a></li>
            {% if user.is_authenticated and user.is_doctor  %}
            <div class="dropdown" style="position: absolute; right: 110px;">
              <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                  @{{ user.username }}
              </a>
              <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'App_Login:doctor_profile' %}">Your Profile</a>
                  <a class="dropdown-item" href="{% url 'Diagnostic_Center:view_prescription' %}">Prescription</a>
                  <a class="dropdown-item" href="{% url 'Diagnostic_Center:view_test_report' %}">Test Reports </a>
                  <a class="dropdown-item" href="{% url 'Diagnostic_Center:view_package_test_report' %}">Package Test Reports </a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a>
              </div>
          </div>
          <br>
              <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Appointment</a>
                <div class="dropdown-menu">
                  <a class="dropdown-item"  href="{% url 'Diagnostic_Center:view_appointment_doctor' %}">My Appointments</a>
                </div>
              
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'App_Login:view_doctor' %}"> Doctors </a>
            </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'Diagnostic_Center:view_test' %}">Tests</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Diagnostic_Center:view_package' %}">Packages</a>
           </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Diagnostic_Center:view_medicine' %}">Medicines</a>
          </li>
            {% elif user.is_authenticated and user.is_technician  %}
            <div class="nav-item dropdown" style="position: absolute; right: 110px;">
              <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                @{{user.username}}
              </a>
              <div class="dropdown-menu">
               <a class="dropdown-item" href="{% url 'App_Login:technician_profile' %}">Your Profile</a>
               <a class="dropdown-item" href="{% url 'Diagnostic_Center:view_test_report' %}">Test Reports </a>
               <a class="dropdown-item" href="{% url 'Diagnostic_Center:view_package_test_report' %}">Package Test Reports </a>
                <a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a>
                <hr>
              </div>
              
            </div>
            <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Appointment</a>
              <div class="dropdown-menu">
                <a class="dropdown-item"  href="{% url 'Diagnostic_Center:view_appointment_test' %}">Appointment For Test</a>
                <a class="dropdown-item"  href="{% url 'Diagnostic_Center:view_appointment_package_test' %}">Appointment For Package Test</a>
              </div>
            
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'App_Login:view_doctor' %}"> Doctors </a>
          </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Diagnostic_Center:view_test' %}">Tests</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Diagnostic_Center:view_package' %}">Packages</a>
        </li>
        
            
            
            {% elif user.is_authenticated and user.is_dcmadmin %}
            <div class="nav-item dropdown" style="position: absolute; right: 110px;">
              <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                @{{user.username}}
              </a>
              <div class="dropdown-menu">
               <a class="dropdown-item" href="{% url 'App_Login:dcmadmin_profile' %}">Your Profile</a>
               <a class="dropdown-item" href="{% url 'Diagnostic_Center:view_test_report' %}">Test Reports </a>
               <a class="dropdown-item" href="{% url 'Diagnostic_Center:view_package_test_report' %}">Package Test Reports </a>
                <a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a>
                <hr>
              </div>
              
            </div>
            <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Appointment</a>
              <div class="dropdown-menu">
                <a class="dropdown-item"  href="{% url 'Diagnostic_Center:view_appointment_doctor' %}">Appointment For Doctor</a>
                <a class="dropdown-item"  href="{% url 'Diagnostic_Center:view_appointment_test' %}">Appointment For Test</a>
                <a class="dropdown-item"  href="{% url 'Diagnostic_Center:view_appointment_package_test' %}">Appointment For Package Test</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'App_Login:view_doctor' %}"> Doctors </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'App_Login:view_technician' %}"> Technicians </a>
        </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Diagnostic_Center:view_test' %}">Tests</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Diagnostic_Center:view_package' %}">Packages</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'Diagnostic_Center:view_medicine' %}">Medicines</a>
        </li>

     
        {% elif user.is_authenticated %}
        <div class="nav-item dropdown" style="position: absolute; right: 120px;">
          <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
            @{{user.username}}
          </a>
          <div class="dropdown-menu">
           <a class="dropdown-item" href="{% url 'App_Login:profile' %}">Your Profile</a>
            <a class="dropdown-item"  href="{% url 'App_Login:view_patient' %}"> Patient</a>
            <a class="dropdown-item"  href="{% url 'Diagnostic_Center:view_prescription' %}"> Prescription</a>
            <a class="dropdown-item" href="{% url 'Diagnostic_Center:view_test_report' %}">Test Reports </a>
            <a class="dropdown-item" href="{% url 'Diagnostic_Center:view_package_test_report' %}">Package Test Reports </a>
            <a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a>
            <hr>
          </div>
          
        </div>
        <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Appointment</a>
          <div class="dropdown-menu">
            <a class="dropdown-item"  href="{% url 'Diagnostic_Center:view_appointment_doctor' %}">Appointment For Doctor</a>
            <a class="dropdown-item"  href="{% url 'Diagnostic_Center:view_appointment_test' %}">Appointment For Test</a>
            <a class="dropdown-item"  href="{% url 'Diagnostic_Center:view_appointment_package_test' %}">Appointment For Package Test</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'App_Login:view_doctor' %}"> Doctors </a>
      </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'Diagnostic_Center:view_test' %}">Tests</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'Diagnostic_Center:view_package' %}">Packages</a>
    </li>
    
    
    {% else %}
    <ul class="navbar-nav ml-auto">
       <li class="nav-item"  style="position: absolute; right: 80px;" >
          <a class="nav-link" href="{% url 'App_Login:signup' %}" >Signup</a>
        </li>
        <li class="nav-item" style="position: absolute; right: 30px;">
          <a class="nav-link" href="{% url 'App_Login:login' %}">Login</a>
         </li>
        </ul>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'App_Login:view_doctor' %}"> Doctors </a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="{% url 'Diagnostic_Center:view_test' %}">Tests</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'Diagnostic_Center:view_package' %}">Packages</a>
     </li>
     
    
      {% endif %}
          {% if request.user.is_staff %}
       
            <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Technician</a>
            <div class="dropdown-menu">
              
              <a class="dropdown-item"  href="{% url 'App_Login:view_technician' %}">Technicians</a>
            </div>
           </li>
           <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Admins</a>
            <div class="dropdown-menu">
              
              <a class="dropdown-item"  href="{% url 'App_Login:view_dcmadmin' %}">Admins</a>
            </div>
           </li>
          </li>
          {% endif %}
        </ul>
    </nav>
    <div class="container" style="padding-top: 20px">
        {% block body_block %} 
        {% endblock %}
    </div>
</body>
</html>